// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lianshenginc_api.Models;

public partial class FactoryUser
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string City { get; set; }
}