// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace lianshenginc_api.Models;

public partial class LianShengFactoryContext : DbContext
{
    public LianShengFactoryContext()
    {
    }

    public LianShengFactoryContext(DbContextOptions<LianShengFactoryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FactoryUser> FactoryUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FactoryUser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__FactoryU__1788CC4C23A63FBA");

            entity.ToTable("FactoryUser");

            entity.Property(e => e.Address)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}